In [1]:
import numpy as np
import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
from scipy.io import loadmat

In [3]:
data = loadmat('machine-learning-ex3/ex3/ex3data1.mat')
X0 = data['X']
X = np.hstack([np.ones((X0.shape[0], 1)), X0])
y = data['y'][:, 0]

In [4]:
X.shape, X.dtype

((5000, 401), dtype('float64'))

In [5]:
y.shape, y.dtype

((5000,), dtype('uint8'))

In [16]:
a = np.arange(10)
a[a> 5] = 100
a

array([  0,   1,   2,   3,   4,   5, 100, 100, 100, 100])

In [6]:
data = loadmat('machine-learning-ex3/ex3/ex3weights.mat')
Theta1 = data['Theta1']
Theta2 = data['Theta2']

In [7]:
Theta1.shape, Theta1.dtype

((25, 401), dtype('<f8'))

In [8]:
Theta2.shape, Theta2.dtype

((10, 26), dtype('<f8'))

# Define Neural Network

In [9]:
n_samples = X.shape[0]
n_input_features = X.shape[1]
n_units_hidden_layer = Theta1.shape[0] + 1
n_untis_output_layer = Theta2.shape[0]

assert Theta1.shape[1] == n_input_features
assert Theta2.shape[1] == n_units_hidden_layer

In [11]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

## Prediction

Prediction by feed-forward:

In [12]:
a1 = X
a2 = sigmoid(a1 @ Theta1.T)
a2 = np.hstack([np.ones((a2.shape[0], 1)), a2])
a3 = sigmoid(a2 @ Theta2.T)
y_pred = a3.argmax(1) + 1
y_pred.shape

(5000,)

In [13]:
y_pred

array([10, 10, 10, ...,  9,  9,  9])

In [15]:
y

array([10, 10, 10, ...,  9,  9,  9], dtype=uint8)